### ISSUE TITLE
Collisional frequency not converting in GENE 

### ISSUE THREAD

**Issue by bpatel2107** [bpatel2107/pyrokinetics#138]
Without reference values the collision frequency is not converting correctly.

Running `example_gene.py`  results in the following error. Surprised the tests didn't catch this but the other template files happens to have `nu=0` so that may be why.

I thought the individual transformations were handled but it looks like it gets a NaN when converting

```
Traceback (most recent call last):
  File "/home/ir-pate3/pyrokinetics/pyrokinetics/normalisation.py", line 862, in convert_dict
    value = value.to(norm).magnitude
  File "/home/ir-pate3/pyrokinetics/pyrokinetics/normalisation.py", line 221, in to
    return self._replace_nan(value, other)
  File "/home/ir-pate3/pyrokinetics/pyrokinetics/normalisation.py", line 167, in _replace_nan
    raise PyroNormalisationError(system, self.units)
pyrokinetics.normalisation.PyroNormalisationError: Cannot convert 'vref_nrl / lref_major_radius' to 'gs2_input0000' normalisation. Possibly 'gs2_input0000' is missing physical reference values. You may need to load a kinetics or equilibrium file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ir-pate3/pyro_testing/example_gene.py", line 9, in <module>
    pyro.gk_code = "GS2"
  File "/home/ir-pate3/pyrokinetics/pyrokinetics/pyro.py", line 302, in gk_code
    self._switch_gk_context(value, force_overwrite=False)
  File "/home/ir-pate3/pyrokinetics/pyrokinetics/pyro.py", line 430, in _switch_gk_context
    self.update_gk_code()
  File "/home/ir-pate3/pyrokinetics/pyrokinetics/pyro.py", line 489, in update_gk_code
    self.gk_input.set(
  File "/home/ir-pate3/pyrokinetics/pyrokinetics/gk_code/GKInputGS2.py", line 525, in set
    self.data[name] = convert_dict(namelist, local_norm.gs2)
  File "/home/ir-pate3/pyrokinetics/pyrokinetics/normalisation.py", line 864, in convert_dict
    raise ValueError(
ValueError: Couldn't convert 'vnewk' (0.0002813941179127954 vref_nrl / lref_major_radius) to gs2 normalisation. This is probably because it did not contain physical reference values. To fix this, please add a geometry and/or kinetic file to your Pyro object.
```

**Comment by bpatel2107** [comment]
Also currently for GENE I think the normalisation treat `lref=R_major` all the time but that is only true if in the input file `gk_input['geometry']['major_R'] = 1`

By default we set `minor_r=1` so I think we need to check this and force `lref` accordingly.  I'm fine to leave `R_major` as the default for now.

What this means is that currently the collisionality is out by a factor of aspect ratio
