### ISSUE TITLE
numpy version installed by pip incompatible with freegs

### ISSUE THREAD

**Issue by nmandell** [bpatel2107/pyrokinetics#187]
I just tried installing via pip, and it automatically upgraded my numpy version to 1.24.2. However, this numpy seems to be incompatible with FreeGS, because I get the following error. Downgrading numpy to 1.20.3 fixes the issue.

$ python3 -m pyrokinetics
/Users/nmandell/miniconda3/envs/gxenv/lib/python3.11/site-packages/freegs/machine.py:293: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  (str("control"), np.bool),
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/Users/nmandell/Codes/pyrokinetics/pyrokinetics/__init__.py", line 26, in <module>
    from .pyro import Pyro
  File "/Users/nmandell/Codes/pyrokinetics/pyrokinetics/pyro.py", line 10, in <module>
    from .gk_code import GKInput, gk_inputs, gk_output_readers
  File "/Users/nmandell/Codes/pyrokinetics/pyrokinetics/gk_code/__init__.py", line 1, in <module>
    from .GKInput import GKInput, gk_inputs
  File "/Users/nmandell/Codes/pyrokinetics/pyrokinetics/gk_code/GKInput.py", line 10, in <module>
    from ..local_geometry import LocalGeometry
  File "/Users/nmandell/Codes/pyrokinetics/pyrokinetics/local_geometry/__init__.py", line 2, in <module>
    from .LocalGeometryMiller import LocalGeometryMiller, default_miller_inputs
  File "/Users/nmandell/Codes/pyrokinetics/pyrokinetics/local_geometry/LocalGeometryMiller.py", line 6, in <module>
    from ..equilibrium import Equilibrium
  File "/Users/nmandell/Codes/pyrokinetics/pyrokinetics/equilibrium/__init__.py", line 4, in <module>
    from .EquilibriumReaderGEQDSK import EquilibriumReaderGEQDSK
  File "/Users/nmandell/Codes/pyrokinetics/pyrokinetics/equilibrium/EquilibriumReaderGEQDSK.py", line 11, in <module>
    from freegs import _geqdsk
  File "/Users/nmandell/miniconda3/envs/gxenv/lib/python3.11/site-packages/freegs/__init__.py", line 34, in <module>
    from .equilibrium import Equilibrium
  File "/Users/nmandell/miniconda3/envs/gxenv/lib/python3.11/site-packages/freegs/equilibrium.py", line 22, in <module>
    from . import machine
  File "/Users/nmandell/miniconda3/envs/gxenv/lib/python3.11/site-packages/freegs/machine.py", line 273, in <module>
    class Solenoid:
  File "/Users/nmandell/miniconda3/envs/gxenv/lib/python3.11/site-packages/freegs/machine.py", line 293, in Solenoid
    (str("control"), np.bool),
                     ^^^^^^^
  File "/Users/nmandell/miniconda3/envs/gxenv/lib/python3.11/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'bool_'?
(gxenv) Noahs-MBP-2:pyrokinetics nmandell$ python3 -m pyrokinetics --help
/Users/nmandell/miniconda3/envs/gxenv/lib/python3.11/site-packages/freegs/machine.py:293: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  (str("control"), np.bool),
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/Users/nmandell/Codes/pyrokinetics/pyrokinetics/__init__.py", line 26, in <module>
    from .pyro import Pyro
  File "/Users/nmandell/Codes/pyrokinetics/pyrokinetics/pyro.py", line 10, in <module>
    from .gk_code import GKInput, gk_inputs, gk_output_readers
  File "/Users/nmandell/Codes/pyrokinetics/pyrokinetics/gk_code/__init__.py", line 1, in <module>
    from .GKInput import GKInput, gk_inputs
  File "/Users/nmandell/Codes/pyrokinetics/pyrokinetics/gk_code/GKInput.py", line 10, in <module>
    from ..local_geometry import LocalGeometry
  File "/Users/nmandell/Codes/pyrokinetics/pyrokinetics/local_geometry/__init__.py", line 2, in <module>
    from .LocalGeometryMiller import LocalGeometryMiller, default_miller_inputs
  File "/Users/nmandell/Codes/pyrokinetics/pyrokinetics/local_geometry/LocalGeometryMiller.py", line 6, in <module>
    from ..equilibrium import Equilibrium
  File "/Users/nmandell/Codes/pyrokinetics/pyrokinetics/equilibrium/__init__.py", line 4, in <module>
    from .EquilibriumReaderGEQDSK import EquilibriumReaderGEQDSK
  File "/Users/nmandell/Codes/pyrokinetics/pyrokinetics/equilibrium/EquilibriumReaderGEQDSK.py", line 11, in <module>
    from freegs import _geqdsk
  File "/Users/nmandell/miniconda3/envs/gxenv/lib/python3.11/site-packages/freegs/__init__.py", line 34, in <module>
    from .equilibrium import Equilibrium
  File "/Users/nmandell/miniconda3/envs/gxenv/lib/python3.11/site-packages/freegs/equilibrium.py", line 22, in <module>
    from . import machine
  File "/Users/nmandell/miniconda3/envs/gxenv/lib/python3.11/site-packages/freegs/machine.py", line 273, in <module>
    class Solenoid:
  File "/Users/nmandell/miniconda3/envs/gxenv/lib/python3.11/site-packages/freegs/machine.py", line 293, in Solenoid
    (str("control"), np.bool),
                     ^^^^^^^
  File "/Users/nmandell/miniconda3/envs/gxenv/lib/python3.11/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'bool_'?

**Comment by ZedThree** [comment]
I think that issue might already be fixed in FreeGS. I'll see if we can get a new release of FreeGS out soon that's compatible with latest numpy.

**Comment by LiamPattinson** [comment]
Sorry about this, the dependency on FreeGS was removed in PR https://github.com/pyro-kinetics/pyrokinetics/pull/154, but we haven't made a new release since last October. If you only want to use Pyrokinetics and don't need FreeGS, it should work if you clone the repo and install from there, or use:

```
pip install --upgrade pip
pip install git+https://github.com/pyro-kinetics/pyrokinetics
```

@bpatel2107 @ZedThree Should we make a new release for Pyrokinetics? Would it be worth updating our release schedule so a new release is made every time a big PR is merged?

**Comment by bpatel2107** [comment]
No longer relevant as we use FreeQDSK
