### ISSUE TITLE
Version on PyPI has broken imports

### ISSUE THREAD

**Issue by theo-brown** [bpatel2107/pyrokinetics#207]
Hi all,
The version of `pyrokinetics` on PyPI has broken imports from `freegs`:
```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    from pyrokinetics import Pyro
  File ".../lib/python3.8/site-packages/pyrokinetics/__init__.py", line 26, in <module>
    from .pyro import Pyro
  File ".../lib/python3.8/site-packages/pyrokinetics/pyro.py", line 10, in <module>
    from .gk_code import GKInput, gk_inputs, gk_output_readers
  File ".../lib/python3.8/site-packages/pyrokinetics/gk_code/__init__.py", line 1, in <module>
    from .GKInput import GKInput, gk_inputs
  File ".../lib/python3.8/site-packages/pyrokinetics/gk_code/GKInput.py", line 10, in <module>
    from ..local_geometry import LocalGeometry
  File ".../lib/python3.8/site-packages/pyrokinetics/local_geometry/__init__.py", line 2, in <module>
    from .LocalGeometryMiller import LocalGeometryMiller, default_miller_inputs
  File ".../lib/python3.8/site-packages/pyrokinetics/local_geometry/LocalGeometryMiller.py", line 6, in <module>
    from ..equilibrium import Equilibrium
  File ".../lib/python3.8/site-packages/pyrokinetics/equilibrium/__init__.py", line 4, in <module>
    from .EquilibriumReaderGEQDSK import EquilibriumReaderGEQDSK
  File ".../lib/python3.8/site-packages/pyrokinetics/equilibrium/EquilibriumReaderGEQDSK.py", line 11, in <module>
    from freegs import _geqdsk
ImportError: cannot import name '_geqdsk' from 'freegs' (.../lib/python3.8/site-packages/freegs/__init__.py)
```
This is not the case if I build from source.
The last release was over 9 months ago - might it be worth making an updated release and pushing it to PyPI?
Thanks,
Theo

**Comment by bpatel2107** [comment]
Hi,

Yes this is very much out of date. We have currently undergoing a major refactoring of the code and are waiting until that is complete for releasing a new version. The final updates are in a PR right now so we are close! Once merged we can update it on PyPi. Until then please build from source.

Cheers,
Bhavin
