### ISSUE TITLE
Ignore CGYRO squareness in convert to GS2

### ISSUE THREAD

**Issue by jfparisi** [bpatel2107/pyrokinetics#321]
When converting a CGYRO input file to GS2, maybe ignore squareness parameters `ZETA` and `S_ZETA` in `input.cgyro` since GS2 does not yet support squareness? Currently, pyro throws an error for non-zero `ZETA` and `S_ZETA` in `input.cgyro`:
```pyro convert GS2 "input.cgyro.locpargen" --input_type CGYRO -o "my_gs2_file.in" -g Miller```
gives
```
Traceback (most recent call last):
  File "/u/jparisi/.local/bin/pyro", line 8, in <module>
    sys.exit(entrypoint())
  File "/u/jparisi/.local/lib/python3.10/site-packages/pyrokinetics/cli/entrypoint.py", line 58, in entrypoint
    args.main(args)
  File "/u/jparisi/.local/lib/python3.10/site-packages/pyrokinetics/cli/convert.py", line 165, in main
    pyro.switch_local_geometry(local_geometry=args.geometry)
  File "/u/jparisi/.local/lib/python3.10/site-packages/pyrokinetics/pyro.py", line 1344, in switch_local_geometry
    local_geometry.from_local_geometry(self.local_geometry, show_fit=show_fit)
  File "/u/jparisi/.local/lib/python3.10/site-packages/pyrokinetics/local_geometry/local_geometry.py", line 230, in from_local_geometry
    self.pressure = local_geometry.pressure
AttributeError: 'LocalGeometryMXH' object has no attribute 'pressure'. Did you mean: 'pressure:'?
```

**Comment by jfparisi** [comment]
Just adding that there are other parameters, too, such as the advanced shaping parameters (e.g. `SHAPE_SIN3`), which are not needed for GS2 geometry, but throw an error if defined in the CGYRO input file.

**Comment by bpatel2107** [comment]
Yeah that's a bug should have been fixed recently but it comes from the fact that pyro is trying to convert from MXH geometry to Miller geometry. Nothing to do with the actual conversion though, just a missed if statement. Will push a fix soon.

When doing this conversion pyro fits to the R,Z and Bpol from the input file rather than just dropping the higher moments. May lead to slightly different values though. Wasn't really sure which is best.

**Comment by bpatel2107** [comment]
Made a little PR to fix this. 


@jfparisi when we do convert from MXH to Miller the best "fit" to the original data doesn't end up being the case when `ZETA` and `S_ZETA` are dropped. See below a case with `ZETA=0.1` and `S_ZETA=0.05`

See the following code below

```python
from pyrokinetics import Pyro

# CGYRO with ZETA, S_ZETA
cgyro_template = "cgyro.txt"

pyro = Pyro(gk_file=cgyro_template)

pyro.switch_local_geometry(local_geometry="Miller", show_fit=True)

pyro.write_gk_file(file_name="miller.cgyro")
```

The result has a slightly different `KAPPA` `DELTA` etc. illustrating my point above

![image](https://github.com/pyro-kinetics/pyrokinetics/assets/15210802/7b3305d4-9545-4995-b4a3-93146eb11849)

[cgyro.txt](https://github.com/pyro-kinetics/pyrokinetics/files/15146892/cgyro.txt)

**Comment by ZedThree** [comment]
Does pyro report a goodness-of-fit when doing this sort of conversion?

**Comment by bpatel2107** [comment]
It warns if the fit is bad, see below  (outdated error message though...)

https://github.com/pyro-kinetics/pyrokinetics/blob/116adba562e15ebd0efe5a3ecafff7038631ad70/src/pyrokinetics/local_geometry/miller.py#L217-L222

**Comment by jfparisi** [comment]
Thanks @bpatel2107 @ZedThree I pulled latest `unstable` and can confirm good expected behavior with `pyro convert GS2 "input.cgyro.locpargen" --input_type CGYRO -o "my_gs2_file.in" -g Miller`.

I definitely agree that the Miller prescription in gs2 will not match the MXH. There is not an easy solution. One approach might be feeding gs2 the geometric coefficients `gds2`, `gds21`, etc., from the cgyro MXH equilibrium. This could happen by allowing gs2 to use an input file (`equilibrium_option = 'file'`, I think). Is the juice worth the squeeze? Maybe?

I have routines that already do something very similar to this on an OMFIT branch, but whether it's appropriate for `pyro` is another question.

**Comment by ZedThree** [comment]
@jfparisi Another option is to implement MXH in GS2? Some recent work by @d7919 might make this pretty easy now

**Comment by bpatel2107** [comment]
We do offer the option to calculate the geometry terms in GS2 

https://github.com/pyro-kinetics/pyrokinetics/blob/116adba562e15ebd0efe5a3ecafff7038631ad70/src/pyrokinetics/diagnostics/__init__.py#L255

So someone would just need to write that out in the appropriate format. I have no idea what gridgen files look like @d7919?

I also know that MXH has been implemented in GENE and its seems to work incredibly well for most surfaces so I would agree that adding it to GS2 would be widely beneficial.

**Comment by jfparisi** [comment]
@bpatel2107 @d7919 @ZedThree  I have attached a python script that writes a `grid.out` file that can be read by gs2. The actual file writing begins around line 1338. I agree with Bhavin that MXH is typically a very close fit, and that it would be very, very nice to have in gs2. In my opinion, MXH in gs2 would also reduce the need to read in a geqdsk file for geometry because MXH is very accurate, and gs2's geqdsk reader gives noisy geometric coefficients if the geqdsk file resolution is not high.

[get_new_gs2_grid.txt](https://github.com/pyro-kinetics/pyrokinetics/files/15178002/get_new_gs2_grid.txt)
